import type { AuditResult, DimensionResult, Finding, Severity } from '../types.js';

const ICON: Record<Severity, string> = {
  pass: '✅',
  warn: '⚠️',
  fail: '❌',
  info: 'ℹ️',
};

function readinessLabel(percent: number): string {
  if (percent >= 90) return '優秀';
  if (percent >= 70) return '良好';
  if (percent >= 50) return '要改善';
  if (percent >= 25) return '大幅改善必要';
  return '未整備';
}

function renderFinding(f: Finding): string {
  const parts: string[] = [ICON[f.severity], f.message];
  if (f.file) parts.push(`— \`${f.file}\``);
  return `- ${parts.join(' ')}`;
}

function renderDimension(d: DimensionResult): string {
  const icon = ICON[d.status];
  const header = `### ${icon} ${d.label} — ${d.score}/${d.maxScore}`;
  const summary = `**${d.summary}**`;
  const findingsList = d.findings.length
    ? d.findings.map(renderFinding).join('\n')
    : '（所見なし）';
  return [header, '', summary, '', findingsList].join('\n');
}

export function renderMarkdownReport(result: AuditResult): string {
  const lines: string[] = [];
  const name = result.target.name ?? result.target.path ?? result.target.url ?? '(unnamed)';

  lines.push(`# AIO 監査レポート — ${name}`);
  lines.push('');
  lines.push(`**対象:** \`${result.target.path ?? result.target.url ?? ''}\`  `);
  lines.push(`**種別:** ${result.target.kind}  `);
  lines.push(`**実行日時:** ${result.timestamp}  `);
  lines.push('');
  lines.push(
    `## 🎯 AIO Readiness: **${result.readinessPercent}%** (${result.overallScore}/${result.maxScore}) — ${readinessLabel(result.readinessPercent)}`,
  );
  lines.push('');

  lines.push('## サマリ');
  lines.push('');
  lines.push('| 次元 | スコア | 状態 | 概要 |');
  lines.push('|---|---|---|---|');
  for (const d of result.dimensions) {
    lines.push(`| ${d.label} | ${d.score}/${d.maxScore} | ${ICON[d.status]} | ${d.summary} |`);
  }
  lines.push('');

  lines.push('## 詳細');
  lines.push('');
  for (const d of result.dimensions) {
    lines.push(renderDimension(d));
    lines.push('');
  }

  lines.push('## メタ情報');
  lines.push('');
  lines.push('```json');
  lines.push(JSON.stringify(result.meta, null, 2));
  lines.push('```');
  lines.push('');
  lines.push('---');
  lines.push(
    '*Generated by `@triceratops/aio/audit`. Triceratops LLC AIO（AI Overview対策）サービス.*',
  );

  return lines.join('\n') + '\n';
}
